In [ ]:
import torch

tensor = torch.arange(1, 12, 2)
tensor

In [2]:
tensor.shape

torch.Size([6])

In [3]:
tensor.numel()

6

In [4]:
tensor = tensor.reshape(2, 3)

In [5]:
torch.exp(tensor)

tensor([[2.7183e+00, 2.0086e+01, 1.4841e+02],
        [1.0966e+03, 8.1031e+03, 5.9874e+04]])

In [6]:
tensor

tensor([[ 1,  3,  5],
        [ 7,  9, 11]])

In [7]:
t1 = tensor.reshape(1, 2, 3)
t2 = tensor.reshape(1, 2, 3)

In [8]:
torch.cat((t1, t2), dim=0).shape

torch.Size([2, 2, 3])

In [9]:
torch.cat((t1, t2), dim=1).shape

torch.Size([1, 4, 3])

In [10]:
torch.cat((t1, t2), dim=2).shape


torch.Size([1, 2, 6])

In [11]:
torch.cat((t1, t2), dim=2).shape

torch.Size([1, 2, 6])

In [12]:
tensor[:] = 0

In [13]:
t1

tensor([[[0, 0, 0],
         [0, 0, 0]]])

In [14]:
t2

tensor([[[0, 0, 0],
         [0, 0, 0]]])

In [15]:
t1[0, 1, 1] = 999

In [16]:
t1

tensor([[[  0,   0,   0],
         [  0, 999,   0]]])

In [17]:
t3 = torch.zeros_like(t1)

In [18]:
print(id(t3))
t3 = t1 + t2
print(id(t3))

4397975168
4734228896


In [19]:
t3 = torch.arange(12)
t4 = t3.reshape(2, 6)
t5 = t3.reshape((2, 6))

In [20]:
t5

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

In [21]:
t5.T == t5.T

tensor([[True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True]])

In [22]:
a1 = torch.arange(9)
a1 = a1.reshape(3, 3)

In [23]:
a1[:] = 1
a1[1, 1] = 2
a1[0, 1] = 3

In [24]:
a1 == a1.T

tensor([[ True, False,  True],
        [False,  True,  True],
        [ True,  True,  True]])

In [25]:
s1 = torch.arange(12, dtype=torch.float32).reshape(3, 4)

In [26]:
s1

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [27]:
s2 = s1.clone()

In [28]:
s3 = s1 + s2

In [29]:
s1, s2, s3

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.]]))

In [30]:
s1[0, 0] = 10

In [31]:
id(s1), id(s2), id(s3)

(4749590592, 4749494928, 4749494368)

In [32]:
s4 = s1

In [33]:
id(s1), id(s4), id(s3)


(4749590592, 4749590592, 4749494368)

In [34]:
s1 * s3

tensor([[  0.,   2.,   8.,  18.],
        [ 32.,  50.,  72.,  98.],
        [128., 162., 200., 242.]])

In [35]:
s1

tensor([[10.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [36]:
s1.sum(axis=[0])

tensor([22., 15., 18., 21.])

In [37]:
s1.mean(axis=[0])

tensor([7.3333, 5.0000, 6.0000, 7.0000])

In [38]:
s1.sum(axis=[0], keepdims=True), s1.sum(axis=[1], keepdims=True),

(tensor([[22., 15., 18., 21.]]),
 tensor([[16.],
         [22.],
         [38.]]))

In [39]:
s1 / s1.sum(axis=[0], keepdims=True), s1 / s1.sum(axis=[1], keepdims=True)

(tensor([[0.4545, 0.0667, 0.1111, 0.1429],
         [0.1818, 0.3333, 0.3333, 0.3333],
         [0.3636, 0.6000, 0.5556, 0.5238]]),
 tensor([[0.6250, 0.0625, 0.1250, 0.1875],
         [0.1818, 0.2273, 0.2727, 0.3182],
         [0.2105, 0.2368, 0.2632, 0.2895]]))

In [40]:
v1 = torch.arange(4, dtype=torch.float32)
torch.dot(v1, v1), v1 * v1

(tensor(14.), tensor([0., 1., 4., 9.]))

In [41]:
torch.mv(s1, v1).shape

torch.Size([3])

In [42]:
s1[0, 0] = 0
torch.mm(s1, s2.T)

tensor([[ 14.,  38.,  62.],
        [ 38., 126., 214.],
        [ 62., 214., 366.]])

In [43]:
torch.norm(s1, keepdim=True), torch.norm(s1)


(tensor([[22.4944]]), tensor(22.4944))

In [44]:
torch.abs(s1).sum()

tensor(66.)

In [45]:
c1 = torch.arange(12).reshape(2, 2, 3)
c1

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])

In [46]:
c1.sum()

tensor(66)

In [47]:
c1.sum(axis=[1, 2],keepdims=True)

tensor([[[15]],

        [[51]]])

In [48]:
c1.sum(axis=[0],keepdims=True)

tensor([[[ 6,  8, 10],
         [12, 14, 16]]])

In [50]:
q1 = torch.arange(4).reshape(2,2)
torch.sum(q1*q1)

tensor(14)