In [1]:
import torch

In [2]:
data = torch.randn(2, 3, requires_grad=True)

In [3]:
data

tensor([[-1.5939,  1.1504,  1.0389],
        [ 0.2931, -1.1172, -0.0987]], requires_grad=True)

In [4]:
res = data * 2 + data ** 2 + 3
res.sum().backward()

In [5]:
print(data.grad)

tensor([[-1.1879,  4.3007,  4.0777],
        [ 2.5861, -0.2345,  1.8027]])


In [7]:
dec_valid_lens = torch.arange(
                1, 3 + 1).repeat(2, 1)
dec_valid_lens

tensor([[1, 2, 3],
        [1, 2, 3]])